[package]
name = "mp3dump"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
hound = "3.5.1"
minimp3 = "0.5.1"
term_size = "0.3.2"
tuple_utils = "0.4.0"
