[package]
name = "video"
version = "0.1.0"
edition = "2021"

[dependencies]
apodize = "1.0.0"
clap = { version = "4.5.4", features = ["derive"] }
minimp3 = "0.5.1"
mtpng = "0.3.5"
realfft = "3.3.0"
tuple-map = "0.4.0"
tuple_utils = "0.4.0"
